= Relational Database Using Aurora
:!toc-title:
:!toc-placement:
:toc:

Set up a PostgreSQL or MySQL database using AWS Aurora with sane defaults.

toc::[]

== About

This module provides an PostgreSQL or MySQL instance using AWS Aurora.
Using this module, you don't have to worry about backups or managing hosts.

== Usage

Place this module together with your microservice infrastructure.

[source,hcl]
----
module "database" {
  source = "github.com/nsbno/terraform-aws-relational-database?ref=x.y.z"

  application_name = "tut-tut-tog"

  engine         = "postgresql"
  engine_version = "13"

  vpc_id             = "vpc-12345"
  subnet_ids         = ["subnet-1a2b3c", "subnet-4b5c6d", "subnet-7a8b9c"]
  availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  security_group_ids = ["sg-54321"]
}
----

This will give you everything you need to use your database.
You don't have to configure anything else unless you have specific requirements 🎉

== Considerations when creating a database cluster

You still have to make some decisions about your database, even though it's managed.
Here are some things to look out for.

=== Choosing Instance Types

The instance type you should choose is based on your workload.
By default, a `db.t3.large` is used, which should be enough for your initial deployment (and maybe forever for smaller apps).

In short you must select the instance type that

* allows for the amount of connections you actually need
* has enough temporary storage to hold your queries and index builds in memory.

You can find out more about what the different instance types allow for in link:https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Managing.html[the management docs for Aurora].

When your application is in production, you can also monitor the impact of your instance type by checking the `VolumeReadIOPS` and `BufferCacheHitRatio` metrics.
The Read IOPS should stay low and the buffer cache hit ratio should stay high.
Values that don't match this can indicate that you should upgrade to a larger instance type.

=== Picking versions for the database

The engine version constraint can take a few different forms.
Either just a major version, or a major and minor version.

For most deployments, it is recommended to _only_ specify the _major_ version.
This is because AWS will automatically upgrade minor versions for you by default.

You should disable automatic minor version upgrades if you need a specific minor version of your engine.
This can be done by setting `allow_minor_version_upgrade` to `false`.
