= Relational Database Using Aurora
:!toc-title:
:!toc-placement:
:toc:

Set up a PostgreSQL or MySQL database using AWS Aurora with sane defaults.

toc::[]

== About

This module provides an PostgreSQL or MySQL instance using AWS Aurora.
Using this module, you don't have to worry about backups or managing hosts.

== Usage

Place this module together with your microservice infrastructure.

[source, hcl]
----
module "database" {
  source = "github.com/nsbno/terraform-aws-relational-database?ref=x.y.z"

  application_name = "tut-tut-tog"

  engine         = "postgresql"
  engine_version = "13"

  vpc_id             = "vpc-12345"
  subnet_ids         = ["subnet-1a2b3c", "subnet-4b5c6d", "subnet-7a8b9c"]
  availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
  security_group_ids = ["sg-54321"]
}
----

This will give you everything you need to use your database.
You don't have to configure anything else unless you have specific requirements 🎉

== Considerations when creating a database cluster

You still have to make some decisions about your database, even though it's managed.
Here are some things to look out for.

=== Picking versions for the database

The engine version constraint can take a few different forms.
Either just a major version, or a major and minor version.

For most deployments, it is recommended to _only_ specify the _major_ version.
This is because AWS will automatically upgrade minor versions for you by default.

You should disable automatic minor version upgrades if you need a specific minor version of your engine.
This can be done by setting `allow_minor_version_upgrade` to `false`.
